###
POST  http://localhost:3333/api/v1/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "username":"ElatighModarator",
    "email":"ElatighModarator@Dwak.com",
    "password":"ElatighModarator",
    "roles":[
        "moderator"
    ]

}
### moderator sign-in
POST  http://localhost:3333/api/v1/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "username":"ElatighModarator",
    "email":"ElatighModarator@Dwak.com",
    "password":"ElatighModarator"
}
###
POST  http://localhost:3333/api/v1/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "username":"Teyibadmin",
    "email":"Teyibadmin@Dwak.com",
    "password":"Teyibadmin"
}
###
POST  http://localhost:3333/api/v1/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "username":"Mouviduser",
    "email":"Mouviduser@Dwak.com",
    "password":"Mouviduser"
}
###

GET http://localhost:3333/api/v1/content/user HTTP/1.1
Content-Type: application/json
###

GET http://localhost:3333/api/v1/content/admin HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjI5MTMyMjI1LCJleHAiOjE2MjkyMTg2MjV9.oc6C8jNptRiraGyELKMTPkDwXufZ6AZ0tfu26nWpP4c

### 
GET http://localhost:3333/api/v1/content/mod HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjI5MTUxOTM5LCJleHAiOjE2MjkyMzgzMzl9.KP31VtwFz-eh50OrAi9-NMIJ60txE2nz0Fir2uMdLmE

### PHONES 
### add phone
POST  http://localhost:3333/api/v1/phones/add-phone HTTP/1.1
Content-Type: application/json

 {
    "price":44500,
    "description":"Phone description",
    "images":"iamge",
    "quantity":4,
    "name":"Iphone 12 Pro Max",
    "memory":256,
    "isUsed":false,
    "ref": "5445566TG33KL"
 }
###  update phone
PUT  http://localhost:3333/api/v1/phones/9 HTTP/1.1
Content-Type: application/json

 {
    "name":"Iphone 12 Pro Max  Update",
    "price":44500,
    "images":"iamge update",
    "quantity":10,
    "ref": "5445566TG33KL updated",
    "description":"Phone description ",
    "isUsed":false,
    "memory":1001
 }
### get phones 
GET  http://localhost:3333/api/v1/phones/ HTTP/1.1
Content-Type: application/json

### delete phone porduct
DELETE  http://localhost:3333/api/v1/phones/18 HTTP/1.1
Content-Type: application/json

### get phone porduct
Get  http://localhost:3333/api/v1/phones/9 HTTP/1.1
Content-Type: application/json

###
## ACCESSORIES
### add phone
POST  http://localhost:3333/api/v1/accessories/add-accessory HTTP/1.1
Content-Type: application/json

{
    "name":"Chargeur Iphone",
    "images":"iamge chargeur",
    "price":100,
    "quantity":58,
    "description":"Chargeur Iphone",
    "ref": "5445566TG33KL",
    "accessory_type":"chargeur",
    "is_original":false
     
}
###  update phone
PUT  http://localhost:3333/api/v1/accessories/24 HTTP/1.1
Content-Type: application/json

{
    "name":"Chargeur Iphone updated",
    "images":"iamge chargeur",
    "price":222,
    "quantity":63,
    "description":"Chargeur Iphone",
    "ref": "5445566TG33KL",
    "accessory_type":"chargeur updated",
    "is_original":false
}
### get phones 
GET  http://localhost:3333/api/v1/accessories/ HTTP/1.1
Content-Type: application/json

### delete phone porduct
DELETE  http://localhost:3333/api/v1/accessories/24 HTTP/1.1
Content-Type: application/json

### get phone porduct
Get  http://localhost:3333/api/v1/accessories/24 HTTP/1.1
Content-Type: application/json

### 