###
POST  http://localhost:3333/api/v1/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "username":"ElatighModarator",
    "email":"ElatighModarator@Dwak.com",
    "password":"ElatighModarator",
    "roles":[
        "moderator"
    ]

}
### moderator sign-in
POST  http://localhost:3333/api/v1/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "username":"ElatighModarator",
    "email":"ElatighModarator@Dwak.com",
    "password":"ElatighModarator"
}
###
POST  http://localhost:3333/api/v1/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "username":"Teyibadmin",
    "email":"Teyibadmin@Dwak.com",
    "password":"Teyibadmin"
}
###
POST  http://localhost:3333/api/v1/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "username":"Mouviduser",
    "email":"Mouviduser@Dwak.com",
    "password":"Mouviduser"
}
###

GET http://localhost:3333/api/v1/content/user HTTP/1.1
Content-Type: application/json
###

GET http://localhost:3333/api/v1/content/admin HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjI5MTMyMjI1LCJleHAiOjE2MjkyMTg2MjV9.oc6C8jNptRiraGyELKMTPkDwXufZ6AZ0tfu26nWpP4c

### 
GET http://localhost:3333/api/v1/content/mod HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjI5MTUxOTM5LCJleHAiOjE2MjkyMzgzMzl9.KP31VtwFz-eh50OrAi9-NMIJ60txE2nz0Fir2uMdLmE

### PHONES 
### add phone
POST  http://localhost:3333/api/v1/phones/add-phone HTTP/1.1
Content-Type: application/json

 {
    "price":44500,
    "description":"The App Store launched 10 years ago. Apps have made the iPhone what it is today, and users wouldn’t find the device as valuable without them. In a decade, the App Store has redefined the way we live: it’s enabled countless new businesses, created millions of jobs and generated entirely new industries. As of this year, the App Store draws in more than 500 million weekly users. Apple makes billions of dollars from the App Store thanks to the mobile app development industry and for this reason, Apple strives to maintain a healthy relationship with developers by acknowledging quality products and featuring their work.",
    "images":["https://images.unsplash.com/photo-1610602699083-1d70b860505b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80", 
    "https://images.unsplash.com/photo-1610602699083-1d70b860505b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"],
    "quantity":4,
    "name":"Iphone 12 Pro Max",
    "memory":256,
    "isUsed":true,
    "ref": "5445566TG33KL"
 }
###  update phone
PUT  http://localhost:3333/api/v1/phones/9 HTTP/1.1
Content-Type: application/json

 {
    "name":"Iphone 12 Pro Max  Update",
    "price":44500,
    "images":"iamge update",
    "quantity":10,
    "ref": "5445566TG33KL updated",
    "description":"Phone description ",
    "isUsed":false,
    "memory":1001
 }
### get phones 
GET  http://localhost:3333/api/v1/phones/ HTTP/1.1
Content-Type: application/json

### delete phone porduct
DELETE  http://localhost:3333/api/v1/phones/18 HTTP/1.1
Content-Type: application/json

### get phone porduct
Get  http://localhost:3333/api/v1/phones/1 HTTP/1.1
Content-Type: application/json

###
## ACCESSORIES
### add phone
POST  http://localhost:3333/api/v1/accessories/add-accessory HTTP/1.1
Content-Type: application/json

{
    "name":"Chargeur Iphone",
    "images":[
        "https://images.unsplash.com/photo-1572721546624-05bf65ad7679?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3366&q=80",
        "https://images.unsplash.com/photo-1572721546624-05bf65ad7679?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3366&q=80"
    ],
    "price":100,
    "quantity":58,
    "description":"s have made the iPhone what it is today, and users wouldn’t find the device as valuable without them. In a decade, the App Store has redefined the way we live: it’s enabled countless new businesses, created millions of jobs and generated entirely new industries. As of this year, the App Store draws in more than 500 million weekly users. Apple makes billio",
    "ref": "5445566TG33KL",
    "accessory_type":"chargeur",
    "is_original":true
     
}
###  update phone
PUT  http://localhost:3333/api/v1/accessories/24 HTTP/1.1
Content-Type: application/json

{
    "name":"Chargeur Iphone updated",
    "images":["https://images.unsplash.com/photo-1610602699083-1d70b860505b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80", 
    "https://images.unsplash.com/photo-1610602699083-1d70b860505b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80"],
    "price":222,
    "quantity":63,
    "description":"Chargeur Iphone",
    "ref": "5445566TG33KL",
    "accessory_type":"chargeur updated",
    "is_original":false
}
### get accessories 
GET  http://localhost:3333/api/v1/accessories/ HTTP/1.1
Content-Type: application/json

### delete phone porduct
DELETE  http://localhost:3333/api/v1/accessories/24 HTTP/1.1
Content-Type: application/json

### get phone porduct
Get  http://localhost:3333/api/v1/accessories/24 HTTP/1.1
Content-Type: application/json

### 